# debug config
debug: true
# training config
optimizer_type: SGD
dataset_type: Cora
gpu_id: 0
gpu_ids: [0, 1]
batch_size_single: 32
use_sbn: true
model_type: DGCNN
hidden_layers: [256, 512, 256]
model_name: DGCNNClassifier256-512-512
lr: 1e-4
T_0: 200
T_mult: 1
beg_epochs: 0
total_epochs: 500
# label noise config
label_noise: 0.4
# misc config
milestone_path: null
milestone_save_epochs: 10
report_iterations: 10